// Auto-generated by scripts/generate-homepage-en.mjs — do not edit manually
// Re-run: node scripts/generate-homepage-en.mjs

export const STORE = {
  "name": "Noeen Platform for Electronic Services",
  "logo": "https://cdn.salla.sa/cdn-cgi/image/fit=scale-down,width=400,height=400,onerror=redirect,format=auto/RlDV/CtuhQhs1wqQazzRZ2O9mQd2dBeU6dh79ZLlUVsRM.png",
  "favicon": "https://cdn.salla.sa/RlDV/WmocG1vS9Zu4s16Q7RN4S4MZB7gXDi6teG4TZ42l.png"
};

export const HEADER_UI = {
  "locale": {
    "language": "English",
    "currencyIcon": "sicon-sar"
  },
  "searchLabel": "Search",
  "login": {
    "heading": "My Account",
    "action": "Sign In"
  },
  "cart": {
    "label": "Cart"
  },
  "menuTitle": "Main Menu",
  "viewAll": "View All",
  "searchModal": {
    "title": "No results found",
    "description": "Nothing here yet, please try again"
  },
  "testimonialsTitle": "Customer Reviews"
};

export const NAV_LINKS = [
  {
    "id": "offers",
    "label": "Offers",
    "href": "/offers",
    "children": []
  },
  {
    "id": "1687021798",
    "label": "All",
    "href": "/category/lvorG",
    "children": []
  },
  {
    "id": "1564829223",
    "label": "Employees",
    "href": "/category/vopgp",
    "children": []
  },
  {
    "id": "894140414",
    "label": "Job Seekers",
    "href": "/category/lRppe",
    "children": []
  },
  {
    "id": "118595327",
    "label": "Students",
    "href": "/category/jRYYR",
    "children": []
  },
  {
    "id": "1358872056",
    "label": "Tests",
    "href": "/category/BxQQB",
    "children": []
  },
  {
    "id": "584834297",
    "label": "Social Development",
    "href": "/category/roppz",
    "children": []
  },
  {
    "id": "1442637881",
    "label": "Finances",
    "href": "/category/joKqXy",
    "children": []
  },
  {
    "id": "1034732737",
    "label": "General Services",
    "href": "/category/bAYYK",
    "children": []
  },
  {
    "id": "2090925050",
    "label": "Appointment Booking",
    "href": "/category/woppB",
    "children": [
      {
        "id": "1107874169",
        "label": "مواعيد حكومية",
        "href": "/category/PQwjvV"
      },
      {
        "id": "1773281147",
        "label": "مواعيد المستشفيات",
        "href": "/category/pqdmYr"
      },
      {
        "id": "1000291908",
        "label": "مواعيد الزيارة",
        "href": "/category/GAOWaW"
      }
    ]
  },
  {
    "id": "687207909",
    "label": "Freelancing",
    "href": "/category/bEGnX",
    "children": [
      {
        "id": "898636097",
        "label": "الإصدار والتسجيل",
        "href": "/category/zEdeNd"
      },
      {
        "id": "589784652",
        "label": "الاستعلامات",
        "href": "/category/NQOvba"
      }
    ]
  },
  {
    "id": "409614788",
    "label": "خدمات الاعمال",
    "href": "/category/dWYYK",
    "children": []
  },
  {
    "id": "301631175",
    "label": "Packages",
    "href": "/category/aWGGR",
    "children": []
  }
];

export const HERO_SLIDES = [
  {
    "image": "https://cdn.files.salla.network/homepage/2108864523/dfc4e383-0298-4fbd-9b1b-cb2a49362dc4.webp",
    "alt": "Noeen Platform"
  },
  {
    "href": "/-/c1687021798",
    "image": "https://cdn.files.salla.network/homepage/2108864523/1ea799ba-1fc6-443f-8eb2-c7c127eb867d.webp",
    "alt": "Noeen Platform"
  },
  {
    "image": "https://cdn.files.salla.network/homepage/2108864523/faab2d99-2d4f-43ac-8730-b0c151105328.webp",
    "alt": "Noeen Platform"
  },
  {
    "href": "/whatsapp/send",
    "image": "https://cdn.files.salla.network/homepage/2108864523/f6af10bb-5e06-4323-a406-ebe0f5bef40f.webp",
    "alt": "Noeen Platform"
  }
];

export const PRODUCT_SECTIONS = [
  {
    "id": "best-offers-1-slider",
    "title": "Most Requested",
    "viewAllHref": "/most-Sales-products?noeen_sa",
    "viewAllLabel": "View All",
    "products": [
      {
        "id": "2134151846",
        "name": "Apply for Freelance Cash Financing",
        "url": "/VRByEm",
        "image": "https://cdn.salla.sa/RlDV/I0b7rvI3KKdENltxUmzkjV3iLf2P1BVLztNS3pH5.png",
        "price": 200,
        "rating": 5
      },
      {
        "id": "1715958792",
        "name": "Freelance Certificate - Specialized Services",
        "url": "/YzwGZD",
        "image": "https://cdn.salla.sa/RlDV/flQulGssZmuaRgYK73fDet7LYvXWCYkNSaiUqK5q.jpeg",
        "price": 70,
        "rating": 5
      },
      {
        "id": "655956466",
        "name": "Apply for REEF Support",
        "url": "/ZloYgO",
        "image": "https://cdn.salla.sa/RlDV/P0U3F1YHKFPQV4tpaavUSRL64vKGiZHhTkd0IEsS.png",
        "price": 150,
        "rating": 5
      },
      {
        "id": "930861569",
        "name": "Freelance Certificate - Productive Families",
        "url": "/PQddQn",
        "image": "https://cdn.salla.sa/RlDV/SK5YRgQRroQSedkgaaAWZrNF3GwQM23RODso114i.png",
        "price": 70,
        "rating": 5
      },
      {
        "id": "286991082",
        "name": "Apply for Guided Transport Freelance Support",
        "url": "/OlnXqg",
        "image": "https://cdn.salla.sa/RlDV/ub4CEbrehbThAf1oUUlLDqdqAlu7ifi6HcnfoyNO.jpg",
        "price": 40,
        "rating": 5
      },
      {
        "id": "37538707",
        "name": "Inquiry about REEF Activities",
        "url": "/pDWzKx",
        "image": "https://cdn.salla.sa/RlDV/4qluzL5LYTfjonnocVbP6T1eftB8qnecGtAE04mx.png",
        "price": 20,
        "rating": 5
      },
      {
        "id": "507931762",
        "name": "Extract Electronic Mudd & Wages Certificate from GOSI",
        "url": "/DGQPblw",
        "image": "https://cdn.salla.sa/RlDV/cwov46tzIe3939XqKUBn9NNxmXsIaclvj4Sgyakn.png",
        "price": 39,
        "rating": 5
      }
    ]
  },
  {
    "id": "best-offers-3-slider",
    "title": "New at Noeen",
    "viewAllHref": "/latest-products",
    "viewAllLabel": "View All",
    "products": [
      {
        "id": "1937222150",
        "name": "Renew QIWA Business Subscription",
        "url": "/KRpYErq",
        "image": "https://cdn.salla.sa/cdn-cgi/image/fit=scale-down,width=400,height=400,onerror=redirect,format=auto/RlDV/CtuhQhs1wqQazzRZ2O9mQd2dBeU6dh79ZLlUVsRM.png",
        "price": 30,
        "rating": 5
      },
      {
        "id": "612211139",
        "name": "Objection or Complaint in Sakani",
        "url": "/ABRPRBE",
        "image": "https://cdn.salla.sa/cdn-cgi/image/fit=scale-down,width=400,height=400,onerror=redirect,format=auto/RlDV/CtuhQhs1wqQazzRZ2O9mQd2dBeU6dh79ZLlUVsRM.png",
        "price": 30,
        "rating": 5
      },
      {
        "id": "874458129",
        "name": "Maternity Compensation Request for Female Employees",
        "url": "/bwnjDPg",
        "image": "https://cdn.salla.sa/cdn-cgi/image/fit=scale-down,width=400,height=400,onerror=redirect,format=auto/RlDV/CtuhQhs1wqQazzRZ2O9mQd2dBeU6dh79ZLlUVsRM.png",
        "price": 40,
        "rating": 5
      },
      {
        "id": "1359108006",
        "name": "Register on Man Hawluk Delivery Platform",
        "url": "/gyYmbjo",
        "image": "https://cdn.salla.sa/cdn-cgi/image/fit=scale-down,width=400,height=400,onerror=redirect,format=auto/RlDV/CtuhQhs1wqQazzRZ2O9mQd2dBeU6dh79ZLlUVsRM.png",
        "price": 49,
        "rating": 5,
        "badge": "Limited time!"
      }
    ]
  },
  {
    "id": "best-offers-6-slider",
    "title": "Social Development Services",
    "viewAllHref": "/category/roppz",
    "viewAllLabel": "View All",
    "products": [
      {
        "id": "1655869090",
        "name": "Change Password or Update Login Details",
        "url": "/DpPpwP",
        "image": "https://cdn.salla.sa/RlDV/deTdDHDQDdFKu3GWv1GUr4Om2ufKhPBkanROITPs.png",
        "price": 20,
        "rating": 5
      },
      {
        "id": "218159350",
        "name": "Objection to Citizen Account Eligibility or Support Amount",
        "url": "/BrQBeGN",
        "image": "https://cdn.salla.sa/RlDV/5TRehOBjISKKycj1zvAf9LMXcWEmrnsbSAMXHHvW.png",
        "price": 30,
        "rating": 5
      },
      {
        "id": "544546084",
        "name": "Remove Dependent from Social Security",
        "url": "/gZOPQzK",
        "image": "https://cdn.salla.sa/RlDV/znnCP1V5ofr67fovAL8cD5JeQ1Nu6hzeOmxwaMWo.png",
        "price": 1,
        "rating": 3
      },
      {
        "id": "314830519",
        "name": "Add Child Dependent (Under 18) to Social Security",
        "url": "/RAlgpoD",
        "image": "https://cdn.salla.sa/RlDV/bou0QILYVKLcuMjMYgDGBNcyTvpDUctGY0kANk3Y.png",
        "price": 1,
        "rating": 5
      },
      {
        "id": "1002540934",
        "name": "Inquiry about Financial Aid for People with Special Needs",
        "url": "/gZOAwxK",
        "image": "https://cdn.salla.sa/RlDV/ZZU61z5MYH1R34P05FBRnrkra8S2sbDZuqVqPubz.png",
        "price": 49,
        "rating": 5
      },
      {
        "id": "831537051",
        "name": "Traffic Facilitation Card for People with Disabilities",
        "url": "/AzzOmbD",
        "image": "https://cdn.salla.sa/RlDV/9JAFfX0goJOQqiOa7hERMVTLfA912haVOIzGZFqz.png",
        "price": 39,
        "rating": 5
      },
      {
        "id": "246794755",
        "name": "Remove Dependent from Citizen Account",
        "url": "/QPWDqq",
        "image": "https://cdn.salla.sa/RlDV/wAx2652Ow5d4zb3Rj5E1oEAcNDKv6jqbmXx0RmMN.png",
        "price": 29,
        "rating": 5
      },
      {
        "id": "112901477",
        "name": "Reapply for Citizen Account",
        "url": "/AmmQKE",
        "image": "https://cdn.salla.sa/RlDV/A9SeWWm0jnfwQkOuJayOJnppxWsCMEcJxtPZ3Xh0.png",
        "price": 29,
        "rating": 5
      }
    ]
  },
  {
    "id": "best-offers-10-slider",
    "title": "Discover More Services",
    "viewAllLabel": "View All",
    "products": [
      {
        "id": "2037788786",
        "name": "Send Email",
        "url": "/BXQoKw",
        "image": "https://cdn.salla.sa/RlDV/S9gDSSWjUAOywxQwfaRcZLu2fNFlfuy1A434Xxyg.png",
        "price": 20,
        "rating": 5
      },
      {
        "id": "1232635646",
        "name": "Subscribe to Absher Business",
        "url": "/gZEVAvE",
        "image": "https://cdn.salla.sa/RlDV/SdtA6MOJcTxq4vWhFFXLFHrz5qzvLSP3CxihyKov.png",
        "price": 49,
        "rating": 5
      },
      {
        "id": "1665411037",
        "name": "Education Financing from Social Development Bank",
        "url": "/XzPPvdv",
        "image": "https://cdn.salla.sa/RlDV/lmSveBQLTzG88mvArToRryHdJqWfG0dbBjkSrQkT.png",
        "price": 150,
        "rating": 5,
        "badge": "New!!"
      },
      {
        "id": "1991266574",
        "name": "Inquiry about Insurance Entitlements",
        "url": "/YpOyjq",
        "image": "https://cdn.salla.sa/RlDV/P7QVmMIj5XVNO1iYqOYxe8Cs6PnuE5bFMOSmnsOG.png",
        "price": 59,
        "rating": 5
      },
      {
        "id": "137892222",
        "name": "Verify SANED Eligibility",
        "url": "/Zajxlo",
        "image": "https://cdn.salla.sa/RlDV/YK0RUz19DKmN7GPFH3IXQ62DhQh7bjnQnUa4SlQp.png",
        "price": 20,
        "rating": 5
      },
      {
        "id": "612211139",
        "name": "Objection or Complaint in Sakani",
        "url": "/ABRPRBE",
        "image": "https://cdn.salla.sa/cdn-cgi/image/fit=scale-down,width=400,height=400,onerror=redirect,format=auto/RlDV/CtuhQhs1wqQazzRZ2O9mQd2dBeU6dh79ZLlUVsRM.png",
        "price": 30,
        "rating": 5
      },
      {
        "id": "1744943981",
        "name": "Inquiry about REEF Application Eligibility Status",
        "url": "/QnwaaY",
        "image": "https://cdn.salla.sa/RlDV/DVja8zGfiuDNeT0fRej4nk57cKD2dxPMqudAcb8f.png",
        "price": 20,
        "rating": 5
      },
      {
        "id": "280486708",
        "name": "Productive Families Financing from Social Development Bank",
        "url": "/EZnaxRK",
        "image": "https://cdn.salla.sa/cdn-cgi/image/fit=scale-down,width=400,height=400,onerror=redirect,format=auto/RlDV/CtuhQhs1wqQazzRZ2O9mQd2dBeU6dh79ZLlUVsRM.png",
        "price": 169,
        "rating": 5
      }
    ]
  }
];

export const PROMO_BANNERS = [
  {
    "image": "https://cdn.files.salla.network/homepage/2108864523/e582ee8c-627e-4b2c-83d5-7c42bfffb2ff.webp",
    "alt": "Banner"
  },
  {
    "href": "/redirect/pages/2009896378",
    "image": "https://cdn.files.salla.network/homepage/2108864523/7f59e58b-c7d0-42df-b4c7-5ad94d8b120a.webp",
    "alt": "Banner"
  }
];

export const TESTIMONIALS = [
  {
    "name": "بندر السعدي",
    "avatar": "https://cdn.assets.salla.network/prod/stores/themes/default/assets/images/avatar_male.png",
    "quote": "",
    "rating": 5
  },
  {
    "name": "ABDULAZiZ QAHITY",
    "avatar": "https://cdn.assets.salla.network/prod/stores/themes/default/assets/images/avatar_male.png",
    "quote": "Very cooperative",
    "rating": 5
  },
  {
    "name": "Demah Abdullah",
    "avatar": "https://cdn.assets.salla.network/prod/stores/themes/default/assets/images/avatar_female.png",
    "quote": "Shoug was excellent and helpful, may she be blessed 🙏🏾❤️",
    "rating": 5
  },
  {
    "name": "منيره عبدالرحمن",
    "avatar": "https://cdn.assets.salla.network/prod/stores/themes/default/assets/images/avatar_female.png",
    "quote": "Great, I will repeat the experience",
    "rating": 5
  },
  {
    "name": "نورة الغامدي",
    "avatar": "https://cdn.assets.salla.network/prod/stores/themes/default/assets/images/avatar_female.png",
    "quote": "Thank you from the heart to everyone running this work",
    "rating": 5
  }
];

export const TRUST_FEATURES = [
  {
    "icon": "sicon-watch",
    "title": "Service Delivery",
    "description": "As fast as possible"
  },
  {
    "icon": "sicon-shield-check",
    "title": "Privacy & Security",
    "description": "Enjoy a safe experience with full privacy"
  },
  {
    "icon": "sicon-refund",
    "title": "Refund & Exchange for Services",
    "description": "Terms and conditions apply"
  }
];

export const PROCESS_STEPS = [
  {
    "icon": "sicon-cart2",
    "title": "Order the Service",
    "description": "Complete payment"
  },
  {
    "icon": "sicon-whatsapp2",
    "title": "We Contact You",
    "description": "We send requirements"
  },
  {
    "icon": "sicon-star-o",
    "title": "We Submit the Request",
    "description": "And you stay satisfied with our service"
  }
];

export const FOOTER = {
  "about": "Noeen® is the first Saudi platform specialized in data entry and electronic services. We offer 500+ services with experience since 2011. C.R: 1010637616 Unified No: 7017271490 #Noeen_Achievers",
  "logo": "https://cdn.salla.sa/cdn-cgi/image/fit=scale-down,width=400,height=400,onerror=redirect,format=auto/RlDV/CtuhQhs1wqQazzRZ2O9mQd2dBeU6dh79ZLlUVsRM.png",
  "logoAlt": "Noeen Platform for Electronic Services",
  "importantLinksTitle": "Important Links",
  "contactTitle": "Contact Us",
  "socialLinks": [
    {
      "platform": "instagram",
      "href": "https://www.instagram.com/Noeen_sa",
      "label": "instagram"
    },
    {
      "platform": "twitter",
      "href": "https://twitter.com/Noeen_sa",
      "label": "twitter"
    },
    {
      "platform": "snapchat",
      "href": "https://www.snapchat.com/add/Noeen_sa",
      "label": "snapchat"
    },
    {
      "platform": "tiktok",
      "href": "https://www.tiktok.com/@noeen_sa",
      "label": "tiktok"
    }
  ],
  "policyLinks": [
    {
      "label": "Noeen Blog",
      "href": "/blog"
    },
    {
      "label": "Noeen Story",
      "href": "/p/Djev"
    },
    {
      "label": "Affiliate Marketing | Earn With Us",
      "href": "/p/oyjj"
    },
    {
      "label": "Join Noeen Team",
      "href": "/p/ZdbZ"
    },
    {
      "label": "FAQ",
      "href": "/p/ypgb"
    },
    {
      "label": "Refund & Exchange Policy",
      "href": "/p/GvEa"
    },
    {
      "label": "Terms of Use",
      "href": "/p/BpEYy"
    },
    {
      "label": "Privacy Policy",
      "href": "/p/QyrA"
    },
    {
      "label": "Warning About Noeen Impersonators",
      "href": "/p/GKqKE"
    },
    {
      "label": "Complaints & Suggestions",
      "href": "/p/BwnBj"
    },
    {
      "label": "Affiliate Program",
      "href": "https://salla.partners/affiliate"
    }
  ],
  "contacts": [
    {
      "href": "https://wa.me/966533227672",
      "value": "+966533227672"
    },
    {
      "href": "tel:+966533227672",
      "value": "+966533227672"
    },
    {
      "href": "mailto:info@noeen.sa",
      "value": "info@noeen.sa"
    },
    {
      "href": "https://t.me/Noeen_bot",
      "value": "https://t.me/Noeen_bot"
    }
  ],
  "payments": [
    {
      "image": "https://cdn.salla.network/cdn-cgi/image/fit=scale-down,width=58,height=58,onerror=redirect,format=auto/images/payment/mada_mini.png",
      "alt": "mada"
    },
    {
      "image": "https://cdn.salla.network/cdn-cgi/image/fit=scale-down,width=58,height=58,onerror=redirect,format=auto/images/payment/credit_card_mini.png",
      "alt": "credit_card"
    },
    {
      "image": "https://cdn.salla.network/cdn-cgi/image/fit=scale-down,width=58,height=58,onerror=redirect,format=auto/images/payment/bank_mini.png",
      "alt": "bank"
    },
    {
      "image": "https://cdn.salla.network/cdn-cgi/image/fit=scale-down,width=58,height=58,onerror=redirect,format=auto/images/payment/stc_pay_mini.png",
      "alt": "stc_pay"
    },
    {
      "image": "https://cdn.salla.network/cdn-cgi/image/fit=scale-down,width=58,height=58,onerror=redirect,format=auto/images/payment/apple_pay_mini.png",
      "alt": "apple_pay"
    },
    {
      "image": "https://cdn.salla.network/cdn-cgi/image/fit=scale-down,width=58,height=58,onerror=redirect,format=auto/images/payment/customer_wallet_mini.png",
      "alt": "customer_wallet"
    },
    {
      "image": "https://cdn.salla.network/cdn-cgi/image/fit=scale-down,width=58,height=58,onerror=redirect,format=auto/images/payment/cod_mini.png",
      "alt": "COD"
    },
    {
      "image": "https://cdn.salla.network/cdn-cgi/image/fit=scale-down,width=58,height=58,onerror=redirect,format=auto/images/sbc.png",
      "alt": "SBC"
    }
  ],
  "copyright": "All rights reserved | 2026 Noeen Platform for Electronic Services"
};

export const HOME_SECTIONS = [
  {
    "type": "hero",
    "slides": [
      {
        "image": "https://cdn.files.salla.network/homepage/2108864523/dfc4e383-0298-4fbd-9b1b-cb2a49362dc4.webp",
        "alt": "Noeen Platform"
      },
      {
        "href": "/-/c1687021798",
        "image": "https://cdn.files.salla.network/homepage/2108864523/1ea799ba-1fc6-443f-8eb2-c7c127eb867d.webp",
        "alt": "Noeen Platform"
      },
      {
        "image": "https://cdn.files.salla.network/homepage/2108864523/faab2d99-2d4f-43ac-8730-b0c151105328.webp",
        "alt": "Noeen Platform"
      },
      {
        "href": "/whatsapp/send",
        "image": "https://cdn.files.salla.network/homepage/2108864523/f6af10bb-5e06-4323-a406-ebe0f5bef40f.webp",
        "alt": "Noeen Platform"
      }
    ]
  },
  {
    "type": "products",
    "id": "best-offers-1-slider",
    "title": "Most Requested",
    "viewAllHref": "/most-Sales-products?noeen_sa",
    "viewAllLabel": "View All",
    "products": [
      {
        "id": "2134151846",
        "name": "Apply for Freelance Cash Financing",
        "url": "/VRByEm",
        "image": "https://cdn.salla.sa/RlDV/I0b7rvI3KKdENltxUmzkjV3iLf2P1BVLztNS3pH5.png",
        "price": 200,
        "rating": 5
      },
      {
        "id": "1715958792",
        "name": "Freelance Certificate - Specialized Services",
        "url": "/YzwGZD",
        "image": "https://cdn.salla.sa/RlDV/flQulGssZmuaRgYK73fDet7LYvXWCYkNSaiUqK5q.jpeg",
        "price": 70,
        "rating": 5
      },
      {
        "id": "655956466",
        "name": "Apply for REEF Support",
        "url": "/ZloYgO",
        "image": "https://cdn.salla.sa/RlDV/P0U3F1YHKFPQV4tpaavUSRL64vKGiZHhTkd0IEsS.png",
        "price": 150,
        "rating": 5
      },
      {
        "id": "930861569",
        "name": "Freelance Certificate - Productive Families",
        "url": "/PQddQn",
        "image": "https://cdn.salla.sa/RlDV/SK5YRgQRroQSedkgaaAWZrNF3GwQM23RODso114i.png",
        "price": 70,
        "rating": 5
      },
      {
        "id": "286991082",
        "name": "Apply for Guided Transport Freelance Support",
        "url": "/OlnXqg",
        "image": "https://cdn.salla.sa/RlDV/ub4CEbrehbThAf1oUUlLDqdqAlu7ifi6HcnfoyNO.jpg",
        "price": 40,
        "rating": 5
      },
      {
        "id": "37538707",
        "name": "Inquiry about REEF Activities",
        "url": "/pDWzKx",
        "image": "https://cdn.salla.sa/RlDV/4qluzL5LYTfjonnocVbP6T1eftB8qnecGtAE04mx.png",
        "price": 20,
        "rating": 5
      },
      {
        "id": "507931762",
        "name": "Extract Electronic Mudd & Wages Certificate from GOSI",
        "url": "/DGQPblw",
        "image": "https://cdn.salla.sa/RlDV/cwov46tzIe3939XqKUBn9NNxmXsIaclvj4Sgyakn.png",
        "price": 39,
        "rating": 5
      }
    ]
  },
  {
    "type": "banner",
    "image": "https://cdn.files.salla.network/homepage/2108864523/e582ee8c-627e-4b2c-83d5-7c42bfffb2ff.webp",
    "alt": "Banner"
  },
  {
    "type": "products",
    "id": "best-offers-3-slider",
    "title": "New at Noeen",
    "viewAllHref": "/latest-products",
    "viewAllLabel": "View All",
    "products": [
      {
        "id": "1937222150",
        "name": "Renew QIWA Business Subscription",
        "url": "/KRpYErq",
        "image": "https://cdn.salla.sa/cdn-cgi/image/fit=scale-down,width=400,height=400,onerror=redirect,format=auto/RlDV/CtuhQhs1wqQazzRZ2O9mQd2dBeU6dh79ZLlUVsRM.png",
        "price": 30,
        "rating": 5
      },
      {
        "id": "612211139",
        "name": "Objection or Complaint in Sakani",
        "url": "/ABRPRBE",
        "image": "https://cdn.salla.sa/cdn-cgi/image/fit=scale-down,width=400,height=400,onerror=redirect,format=auto/RlDV/CtuhQhs1wqQazzRZ2O9mQd2dBeU6dh79ZLlUVsRM.png",
        "price": 30,
        "rating": 5
      },
      {
        "id": "874458129",
        "name": "Maternity Compensation Request for Female Employees",
        "url": "/bwnjDPg",
        "image": "https://cdn.salla.sa/cdn-cgi/image/fit=scale-down,width=400,height=400,onerror=redirect,format=auto/RlDV/CtuhQhs1wqQazzRZ2O9mQd2dBeU6dh79ZLlUVsRM.png",
        "price": 40,
        "rating": 5
      },
      {
        "id": "1359108006",
        "name": "Register on Man Hawluk Delivery Platform",
        "url": "/gyYmbjo",
        "image": "https://cdn.salla.sa/cdn-cgi/image/fit=scale-down,width=400,height=400,onerror=redirect,format=auto/RlDV/CtuhQhs1wqQazzRZ2O9mQd2dBeU6dh79ZLlUVsRM.png",
        "price": 49,
        "rating": 5,
        "badge": "Limited time!"
      }
    ]
  },
  {
    "type": "testimonials",
    "title": "Customer Reviews",
    "viewAllHref": "/testimonials",
    "viewAllLabel": "View All",
    "items": [
      {
        "name": "بندر السعدي",
        "avatar": "https://cdn.assets.salla.network/prod/stores/themes/default/assets/images/avatar_male.png",
        "quote": "",
        "rating": 5
      },
      {
        "name": "ABDULAZiZ QAHITY",
        "avatar": "https://cdn.assets.salla.network/prod/stores/themes/default/assets/images/avatar_male.png",
        "quote": "Very cooperative",
        "rating": 5
      },
      {
        "name": "Demah Abdullah",
        "avatar": "https://cdn.assets.salla.network/prod/stores/themes/default/assets/images/avatar_female.png",
        "quote": "Shoug was excellent and helpful, may she be blessed 🙏🏾❤️",
        "rating": 5
      },
      {
        "name": "منيره عبدالرحمن",
        "avatar": "https://cdn.assets.salla.network/prod/stores/themes/default/assets/images/avatar_female.png",
        "quote": "Great, I will repeat the experience",
        "rating": 5
      },
      {
        "name": "نورة الغامدي",
        "avatar": "https://cdn.assets.salla.network/prod/stores/themes/default/assets/images/avatar_female.png",
        "quote": "Thank you from the heart to everyone running this work",
        "rating": 5
      }
    ]
  },
  {
    "type": "trust-features",
    "items": [
      {
        "icon": "sicon-watch",
        "title": "Service Delivery",
        "description": "As fast as possible"
      },
      {
        "icon": "sicon-shield-check",
        "title": "Privacy & Security",
        "description": "Enjoy a safe experience with full privacy"
      },
      {
        "icon": "sicon-refund",
        "title": "Refund & Exchange for Services",
        "description": "Terms and conditions apply"
      }
    ]
  },
  {
    "type": "products",
    "id": "best-offers-6-slider",
    "title": "Social Development Services",
    "viewAllHref": "/category/roppz",
    "viewAllLabel": "View All",
    "products": [
      {
        "id": "1655869090",
        "name": "Change Password or Update Login Details",
        "url": "/DpPpwP",
        "image": "https://cdn.salla.sa/RlDV/deTdDHDQDdFKu3GWv1GUr4Om2ufKhPBkanROITPs.png",
        "price": 20,
        "rating": 5
      },
      {
        "id": "218159350",
        "name": "Objection to Citizen Account Eligibility or Support Amount",
        "url": "/BrQBeGN",
        "image": "https://cdn.salla.sa/RlDV/5TRehOBjISKKycj1zvAf9LMXcWEmrnsbSAMXHHvW.png",
        "price": 30,
        "rating": 5
      },
      {
        "id": "544546084",
        "name": "Remove Dependent from Social Security",
        "url": "/gZOPQzK",
        "image": "https://cdn.salla.sa/RlDV/znnCP1V5ofr67fovAL8cD5JeQ1Nu6hzeOmxwaMWo.png",
        "price": 1,
        "rating": 3
      },
      {
        "id": "314830519",
        "name": "Add Child Dependent (Under 18) to Social Security",
        "url": "/RAlgpoD",
        "image": "https://cdn.salla.sa/RlDV/bou0QILYVKLcuMjMYgDGBNcyTvpDUctGY0kANk3Y.png",
        "price": 1,
        "rating": 5
      },
      {
        "id": "1002540934",
        "name": "Inquiry about Financial Aid for People with Special Needs",
        "url": "/gZOAwxK",
        "image": "https://cdn.salla.sa/RlDV/ZZU61z5MYH1R34P05FBRnrkra8S2sbDZuqVqPubz.png",
        "price": 49,
        "rating": 5
      },
      {
        "id": "831537051",
        "name": "Traffic Facilitation Card for People with Disabilities",
        "url": "/AzzOmbD",
        "image": "https://cdn.salla.sa/RlDV/9JAFfX0goJOQqiOa7hERMVTLfA912haVOIzGZFqz.png",
        "price": 39,
        "rating": 5
      },
      {
        "id": "246794755",
        "name": "Remove Dependent from Citizen Account",
        "url": "/QPWDqq",
        "image": "https://cdn.salla.sa/RlDV/wAx2652Ow5d4zb3Rj5E1oEAcNDKv6jqbmXx0RmMN.png",
        "price": 29,
        "rating": 5
      },
      {
        "id": "112901477",
        "name": "Reapply for Citizen Account",
        "url": "/AmmQKE",
        "image": "https://cdn.salla.sa/RlDV/A9SeWWm0jnfwQkOuJayOJnppxWsCMEcJxtPZ3Xh0.png",
        "price": 29,
        "rating": 5
      }
    ]
  },
  {
    "type": "testimonials",
    "title": "Customer Reviews",
    "viewAllHref": "/testimonials",
    "viewAllLabel": "View All",
    "items": [
      {
        "name": "بندر السعدي",
        "avatar": "https://cdn.assets.salla.network/prod/stores/themes/default/assets/images/avatar_male.png",
        "quote": "",
        "rating": 5
      },
      {
        "name": "ABDULAZiZ QAHITY",
        "avatar": "https://cdn.assets.salla.network/prod/stores/themes/default/assets/images/avatar_male.png",
        "quote": "Very cooperative",
        "rating": 5
      },
      {
        "name": "Demah Abdullah",
        "avatar": "https://cdn.assets.salla.network/prod/stores/themes/default/assets/images/avatar_female.png",
        "quote": "Shoug was excellent and helpful, may she be blessed 🙏🏾❤️",
        "rating": 5
      },
      {
        "name": "منيره عبدالرحمن",
        "avatar": "https://cdn.assets.salla.network/prod/stores/themes/default/assets/images/avatar_female.png",
        "quote": "Great, I will repeat the experience",
        "rating": 5
      },
      {
        "name": "نورة الغامدي",
        "avatar": "https://cdn.assets.salla.network/prod/stores/themes/default/assets/images/avatar_female.png",
        "quote": "Thank you from the heart to everyone running this work",
        "rating": 5
      }
    ]
  },
  {
    "type": "banner",
    "href": "/redirect/pages/2009896378",
    "image": "https://cdn.files.salla.network/homepage/2108864523/7f59e58b-c7d0-42df-b4c7-5ad94d8b120a.webp",
    "alt": "Banner"
  },
  {
    "type": "process-steps",
    "items": [
      {
        "icon": "sicon-cart2",
        "title": "Order the Service",
        "description": "Complete payment"
      },
      {
        "icon": "sicon-whatsapp2",
        "title": "We Contact You",
        "description": "We send requirements"
      },
      {
        "icon": "sicon-star-o",
        "title": "We Submit the Request",
        "description": "And you stay satisfied with our service"
      }
    ]
  },
  {
    "type": "products",
    "id": "best-offers-10-slider",
    "title": "Discover More Services",
    "viewAllLabel": "View All",
    "products": [
      {
        "id": "2037788786",
        "name": "Send Email",
        "url": "/BXQoKw",
        "image": "https://cdn.salla.sa/RlDV/S9gDSSWjUAOywxQwfaRcZLu2fNFlfuy1A434Xxyg.png",
        "price": 20,
        "rating": 5
      },
      {
        "id": "1232635646",
        "name": "Subscribe to Absher Business",
        "url": "/gZEVAvE",
        "image": "https://cdn.salla.sa/RlDV/SdtA6MOJcTxq4vWhFFXLFHrz5qzvLSP3CxihyKov.png",
        "price": 49,
        "rating": 5
      },
      {
        "id": "1665411037",
        "name": "Education Financing from Social Development Bank",
        "url": "/XzPPvdv",
        "image": "https://cdn.salla.sa/RlDV/lmSveBQLTzG88mvArToRryHdJqWfG0dbBjkSrQkT.png",
        "price": 150,
        "rating": 5,
        "badge": "New!!"
      },
      {
        "id": "1991266574",
        "name": "Inquiry about Insurance Entitlements",
        "url": "/YpOyjq",
        "image": "https://cdn.salla.sa/RlDV/P7QVmMIj5XVNO1iYqOYxe8Cs6PnuE5bFMOSmnsOG.png",
        "price": 59,
        "rating": 5
      },
      {
        "id": "137892222",
        "name": "Verify SANED Eligibility",
        "url": "/Zajxlo",
        "image": "https://cdn.salla.sa/RlDV/YK0RUz19DKmN7GPFH3IXQ62DhQh7bjnQnUa4SlQp.png",
        "price": 20,
        "rating": 5
      },
      {
        "id": "612211139",
        "name": "Objection or Complaint in Sakani",
        "url": "/ABRPRBE",
        "image": "https://cdn.salla.sa/cdn-cgi/image/fit=scale-down,width=400,height=400,onerror=redirect,format=auto/RlDV/CtuhQhs1wqQazzRZ2O9mQd2dBeU6dh79ZLlUVsRM.png",
        "price": 30,
        "rating": 5
      },
      {
        "id": "1744943981",
        "name": "Inquiry about REEF Application Eligibility Status",
        "url": "/QnwaaY",
        "image": "https://cdn.salla.sa/RlDV/DVja8zGfiuDNeT0fRej4nk57cKD2dxPMqudAcb8f.png",
        "price": 20,
        "rating": 5
      },
      {
        "id": "280486708",
        "name": "Productive Families Financing from Social Development Bank",
        "url": "/EZnaxRK",
        "image": "https://cdn.salla.sa/cdn-cgi/image/fit=scale-down,width=400,height=400,onerror=redirect,format=auto/RlDV/CtuhQhs1wqQazzRZ2O9mQd2dBeU6dh79ZLlUVsRM.png",
        "price": 169,
        "rating": 5
      }
    ]
  }
];

export const ALL_PRODUCTS = [
  {
    "id": "2134151846",
    "name": "Apply for Freelance Cash Financing",
    "url": "/VRByEm",
    "image": "https://cdn.salla.sa/RlDV/I0b7rvI3KKdENltxUmzkjV3iLf2P1BVLztNS3pH5.png",
    "price": 200,
    "rating": 5
  },
  {
    "id": "1715958792",
    "name": "Freelance Certificate - Specialized Services",
    "url": "/YzwGZD",
    "image": "https://cdn.salla.sa/RlDV/flQulGssZmuaRgYK73fDet7LYvXWCYkNSaiUqK5q.jpeg",
    "price": 70,
    "rating": 5
  },
  {
    "id": "655956466",
    "name": "Apply for REEF Support",
    "url": "/ZloYgO",
    "image": "https://cdn.salla.sa/RlDV/P0U3F1YHKFPQV4tpaavUSRL64vKGiZHhTkd0IEsS.png",
    "price": 150,
    "rating": 5
  },
  {
    "id": "930861569",
    "name": "Freelance Certificate - Productive Families",
    "url": "/PQddQn",
    "image": "https://cdn.salla.sa/RlDV/SK5YRgQRroQSedkgaaAWZrNF3GwQM23RODso114i.png",
    "price": 70,
    "rating": 5
  },
  {
    "id": "286991082",
    "name": "Apply for Guided Transport Freelance Support",
    "url": "/OlnXqg",
    "image": "https://cdn.salla.sa/RlDV/ub4CEbrehbThAf1oUUlLDqdqAlu7ifi6HcnfoyNO.jpg",
    "price": 40,
    "rating": 5
  },
  {
    "id": "37538707",
    "name": "Inquiry about REEF Activities",
    "url": "/pDWzKx",
    "image": "https://cdn.salla.sa/RlDV/4qluzL5LYTfjonnocVbP6T1eftB8qnecGtAE04mx.png",
    "price": 20,
    "rating": 5
  },
  {
    "id": "507931762",
    "name": "Extract Electronic Mudd & Wages Certificate from GOSI",
    "url": "/DGQPblw",
    "image": "https://cdn.salla.sa/RlDV/cwov46tzIe3939XqKUBn9NNxmXsIaclvj4Sgyakn.png",
    "price": 39,
    "rating": 5
  },
  {
    "id": "1937222150",
    "name": "Renew QIWA Business Subscription",
    "url": "/KRpYErq",
    "image": "https://cdn.salla.sa/cdn-cgi/image/fit=scale-down,width=400,height=400,onerror=redirect,format=auto/RlDV/CtuhQhs1wqQazzRZ2O9mQd2dBeU6dh79ZLlUVsRM.png",
    "price": 30,
    "rating": 5
  },
  {
    "id": "612211139",
    "name": "Objection or Complaint in Sakani",
    "url": "/ABRPRBE",
    "image": "https://cdn.salla.sa/cdn-cgi/image/fit=scale-down,width=400,height=400,onerror=redirect,format=auto/RlDV/CtuhQhs1wqQazzRZ2O9mQd2dBeU6dh79ZLlUVsRM.png",
    "price": 30,
    "rating": 5
  },
  {
    "id": "874458129",
    "name": "Maternity Compensation Request for Female Employees",
    "url": "/bwnjDPg",
    "image": "https://cdn.salla.sa/cdn-cgi/image/fit=scale-down,width=400,height=400,onerror=redirect,format=auto/RlDV/CtuhQhs1wqQazzRZ2O9mQd2dBeU6dh79ZLlUVsRM.png",
    "price": 40,
    "rating": 5
  },
  {
    "id": "1359108006",
    "name": "Register on Man Hawluk Delivery Platform",
    "url": "/gyYmbjo",
    "image": "https://cdn.salla.sa/cdn-cgi/image/fit=scale-down,width=400,height=400,onerror=redirect,format=auto/RlDV/CtuhQhs1wqQazzRZ2O9mQd2dBeU6dh79ZLlUVsRM.png",
    "price": 49,
    "rating": 5,
    "badge": "Limited time!"
  },
  {
    "id": "1655869090",
    "name": "Change Password or Update Login Details",
    "url": "/DpPpwP",
    "image": "https://cdn.salla.sa/RlDV/deTdDHDQDdFKu3GWv1GUr4Om2ufKhPBkanROITPs.png",
    "price": 20,
    "rating": 5
  },
  {
    "id": "218159350",
    "name": "Objection to Citizen Account Eligibility or Support Amount",
    "url": "/BrQBeGN",
    "image": "https://cdn.salla.sa/RlDV/5TRehOBjISKKycj1zvAf9LMXcWEmrnsbSAMXHHvW.png",
    "price": 30,
    "rating": 5
  },
  {
    "id": "544546084",
    "name": "Remove Dependent from Social Security",
    "url": "/gZOPQzK",
    "image": "https://cdn.salla.sa/RlDV/znnCP1V5ofr67fovAL8cD5JeQ1Nu6hzeOmxwaMWo.png",
    "price": 1,
    "rating": 3
  },
  {
    "id": "314830519",
    "name": "Add Child Dependent (Under 18) to Social Security",
    "url": "/RAlgpoD",
    "image": "https://cdn.salla.sa/RlDV/bou0QILYVKLcuMjMYgDGBNcyTvpDUctGY0kANk3Y.png",
    "price": 1,
    "rating": 5
  },
  {
    "id": "1002540934",
    "name": "Inquiry about Financial Aid for People with Special Needs",
    "url": "/gZOAwxK",
    "image": "https://cdn.salla.sa/RlDV/ZZU61z5MYH1R34P05FBRnrkra8S2sbDZuqVqPubz.png",
    "price": 49,
    "rating": 5
  },
  {
    "id": "831537051",
    "name": "Traffic Facilitation Card for People with Disabilities",
    "url": "/AzzOmbD",
    "image": "https://cdn.salla.sa/RlDV/9JAFfX0goJOQqiOa7hERMVTLfA912haVOIzGZFqz.png",
    "price": 39,
    "rating": 5
  },
  {
    "id": "246794755",
    "name": "Remove Dependent from Citizen Account",
    "url": "/QPWDqq",
    "image": "https://cdn.salla.sa/RlDV/wAx2652Ow5d4zb3Rj5E1oEAcNDKv6jqbmXx0RmMN.png",
    "price": 29,
    "rating": 5
  },
  {
    "id": "112901477",
    "name": "Reapply for Citizen Account",
    "url": "/AmmQKE",
    "image": "https://cdn.salla.sa/RlDV/A9SeWWm0jnfwQkOuJayOJnppxWsCMEcJxtPZ3Xh0.png",
    "price": 29,
    "rating": 5
  },
  {
    "id": "2037788786",
    "name": "Send Email",
    "url": "/BXQoKw",
    "image": "https://cdn.salla.sa/RlDV/S9gDSSWjUAOywxQwfaRcZLu2fNFlfuy1A434Xxyg.png",
    "price": 20,
    "rating": 5
  },
  {
    "id": "1232635646",
    "name": "Subscribe to Absher Business",
    "url": "/gZEVAvE",
    "image": "https://cdn.salla.sa/RlDV/SdtA6MOJcTxq4vWhFFXLFHrz5qzvLSP3CxihyKov.png",
    "price": 49,
    "rating": 5
  },
  {
    "id": "1665411037",
    "name": "Education Financing from Social Development Bank",
    "url": "/XzPPvdv",
    "image": "https://cdn.salla.sa/RlDV/lmSveBQLTzG88mvArToRryHdJqWfG0dbBjkSrQkT.png",
    "price": 150,
    "rating": 5,
    "badge": "New!!"
  },
  {
    "id": "1991266574",
    "name": "Inquiry about Insurance Entitlements",
    "url": "/YpOyjq",
    "image": "https://cdn.salla.sa/RlDV/P7QVmMIj5XVNO1iYqOYxe8Cs6PnuE5bFMOSmnsOG.png",
    "price": 59,
    "rating": 5
  },
  {
    "id": "137892222",
    "name": "Verify SANED Eligibility",
    "url": "/Zajxlo",
    "image": "https://cdn.salla.sa/RlDV/YK0RUz19DKmN7GPFH3IXQ62DhQh7bjnQnUa4SlQp.png",
    "price": 20,
    "rating": 5
  },
  {
    "id": "1744943981",
    "name": "Inquiry about REEF Application Eligibility Status",
    "url": "/QnwaaY",
    "image": "https://cdn.salla.sa/RlDV/DVja8zGfiuDNeT0fRej4nk57cKD2dxPMqudAcb8f.png",
    "price": 20,
    "rating": 5
  },
  {
    "id": "280486708",
    "name": "Productive Families Financing from Social Development Bank",
    "url": "/EZnaxRK",
    "image": "https://cdn.salla.sa/cdn-cgi/image/fit=scale-down,width=400,height=400,onerror=redirect,format=auto/RlDV/CtuhQhs1wqQazzRZ2O9mQd2dBeU6dh79ZLlUVsRM.png",
    "price": 169,
    "rating": 5
  }
];
